### ISSUE TITLE
Getting an Error is_locked violates not-null constraint

### ISSUE THREAD

**Issue by KaffineAddict** [robinjoseph08/go-pg-migrations#14] opened 2019-09-12 23:21 UTC
ERROR #23502 null value in column "is_locked" violates not-null constraint

This occurs when the migration is running any command even the help command as it is trying to insert a migration lock and failing with that error. The SQL being run is the following.

INSERT INTO migration_lock ("id", "is_locked") VALUES ('lock', false) RETURNING "is_locked"

Edit the actual query is:
INSERT INTO migration_lock ("id", "is_locked") VALUES ('lock', DEFAULT) RETURNING "is_locked"

**Comment by robinjoseph08** [comment] 2019-09-15 01:27
Thanks for the report, @KaffineAddict! Could you provide the exact steps/commands you ran to cause this error? I can't seem to replicate it for some reason. And it's a bit odd because if that's the SQL being run, it's setting it to `false`, which is a non-null value, so it shouldn't be erring out.

**Comment by KaffineAddict** [comment] 2019-09-15 06:55
Looks like it's actually setting it to DEFAULT. I copy and pasted the wrong query so I'll add an edit. I believe I have a fix for it and will send you a pull request on Monday. I think it has to do with a pg-go change.

**Comment by yuriploc** [comment] 2019-10-17 13:31
@robinjoseph08 Is this project still active?

**Comment by robinjoseph08** [comment] 2019-10-26 17:15
Apologies for the delay here, everyone! I'll get this PR merged in and cut a new version today!

**Comment by robinjoseph08** [comment] 2019-10-26 17:58
@KaffineAddict @yuriploc I'm gonna merge it in since it shouldn't break backwards compatibility, but I'm still having a hard time trying to reproduce this error myself. Can you give me some details about the project that you saw this in?

- Are you using Go modules or are you using another dependency management system like `dep`?
- If you're using Go modules, do you have any `replace` directives in your `go.mod`? because since `go-pg` switched to Go modules, the import path for it on the v9 betas is `github.com/go-pg/pg/v9`. In that case, since `go-pg-migrations` just uses `github.com/go-pg/pg`, it will actually import v8.0.6, so then this error wouldn't happen.
- What version of `go-pg` are you running? If you can provide the git hash and the version number, that would be helpful!

**Closed** 2019-10-26 18:00 UTC

**Comment by robinjoseph08** [comment] 2019-10-26 19:34
Just cut v1.0.1 (with just this fix) and v2.0.0 with Go modules support. Hopefully with this, these kinds of breaking changes will be less likely. Still curious about the setup that produced this error though.

Thanks for the help!
